### ISSUE TITLE
FatalErrorException in HtmlBuilder.php line 3: Class 'Collective\Html\Htmlbuilder' not found

### ISSUE THREAD

**Issue by agentready** [bestmomo/laravel5-relations#2]
having this issue after installation -->
`FatalErrorException in HtmlBuilder.php line 3: Class 'Collective\Html\Htmlbuilder' not found`

**Comment by bestmomo** [comment]
It's an uppercase issue (I am on Windows and I cant get them). Look at [this commit](https://github.com/bestmomo/laravel5-relations/commit/1167aa26534b546b8c0137ac2b5464907c3b8faf).

**Comment by agentready** [comment]
Thanks , it is now working.

**Comment by bestmomo** [comment]
Perfect, so I close the issue.
